### ISSUE TITLE
[question] origin of labels not in PubLayNet

### ISSUE THREAD

**Issue by mllife** [AILab-UniFI/cte-dataset#1]
where are 'OTHERS' & 'CAPTION' labels coming from?
not present in PubLayNet, PubLayNet only has 5 label categories in it:
- TEXT
- TITLE
- LIST 
- TABLE 
- FIGURE

**Comment by emanuelevivoli** [comment]
Hello @mllife and thank you for your interest!
As you can read from the paper (https://arxiv.org/pdf/2302.01451.pdf page 5):
> Moreover, we added two classes: caption and other. Captions are heuristically found taking into
account the proximity with images and tables, while the other class contains all the remaining
not-labeled text regions (e.g. page headers and page numbers)

Hope it helps :)
Lele
